# this is a comment
# so is this
CONFIGURATION
	CONDITION VCC  #this is too
	CONDITION !START
	CONDITION >16
	CONDITION >4
	CONDITION done
	SIGNAL OP,0,3,10
	SIGNAL LD_X,3,1,10
	SIGNAL LD_Y,4,1,10
	SIGNAL CNT_EN,5,1,10
ENDCONFIGURATION
